### ISSUE TITLE
FYI, the Yarle config accepts a directory

### ISSUE THREAD

**Issue by jdefontes** [dmuth/evernote-to-obsidian#8]
I discovered this by accident after separately converting a bunch of indivudual files... you can put a directory name in `enexSource` and it processes all the `.enex` files it finds in that directory.

**Comment by dmuth** [comment]
Cool!  I'm gonna close this out because it's not technically a bug, but is useful for anyone who may be digging into the internals of this tool.

**Comment by jdefontes** [comment]
For me, finding this made your script unnecessary. But I appreciated having the config file example. Thanks.
